# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll

minimal_mistakes_skin    : "contrast" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en"
title                    : "Domain Storytelling"
title_separator          : "-"
subtitle                 : "Spark a fire. Tell a story. Paint a picture" # site tagline that appears below site title in masthead
name                     : "Stefan Hofer and Henning Schwentner with ❤️ from WPS – Workplace Solutions"
description              : "A collaborative, visual, and agile way to build domain-driven software"
url                      : "https://domainstorytelling.org/" 
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "WPS/domainstorytelling.org" # GitHub username/repo-name
teaser                   : /assets/images/header_dst.jpg # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : /assets/images/logo/square/dst_logo_transparent_no-text.png # path of logo image to display in the masthead, e.g. "/assets/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : false # true, false (default)
words_per_minute         : 200

include:
  - _pages

# Collections
collections:
  articles:
    output: true
    permalink: /:collection/:path/


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

#Klingt interessant, läuft aber wohl nicht auf GHP: jekyll_picture_tag

footer:
  links:
    - label: "Improve this page"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/WPS/domainstorytelling.org"
    - label: "Licensed CC-BY-4.0"
      icon: "fab fa-creative-commons"
      url: "http://creativecommons.org/licenses/by/4.0/"
    - label: "Imprint"
      icon: "fas fa-balance-scale"
      url: "https://www.wps.de/impressum/"
    - label: "Privacy"
      icon: "fas fa-user-shield"
      url: "https://www.wps.de/en/privacy-policy"
    - label: "Contact"
      icon: "fas fa-handshake"
      url: "/contact"

atom_feed:
  hide: true

defaults:
  # _articles
  - scope:
      path: ""
      type: articles
    values:
      layout: single
      author_profile: true
      share: true
