version: "3.9"

services:
  site:
    build: .
    image: wps/domainstorytelling.org:latest
    command: bundle exec jekyll serve --trace --host 0.0.0.0 --watch --incremental
    environment:
      - JEKYLL_ENV=development
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
